name: bulbul_reservasi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11 
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.3.2
  image_picker: ^1.0.7
  
  # TAMBAHAN PENTING UNTUK PAYMENT (Format Tanggal & Uang)
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Pastikan file-file ini BENAR-BENAR ADA di folder laptop Anda
    # assets/images/....
    - assets/images/pantai_landingscreens.jpg
    - assets/images/pondok.jpg
    - assets/images/banana_boat.jpg
    - assets/images/pondok_bulbul.jpg
    - assets/images/tenda.jpeg
    - assets/images/homestay.jpeg